version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, ci]
  - package-ecosystem: npm
    directory: /services/api
    schedule:
      interval: weekly
    labels: [dependencies, javascript]
  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: weekly
    labels: [dependencies, terraform]
  - package-ecosystem: docker
    directory: /services/api
    schedule:
      interval: weekly
    labels: [dependencies, docker]
  - package-ecosystem: docker
    directory: /services/frontend
    schedule:
      interval: weekly
    labels: [dependencies, docker]
