{{- if .Values.secrets.enabled -}}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "k8s-eks-platform.fullname" . }}-aws-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{- include "k8s-eks-platform.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
      {{- range .Values.secrets.names }}
      - objectName: "{{ $.Values.secrets.secretsPrefix }}/{{ $.Values.global.environment }}/{{ . }}"
        objectType: "secretsmanager"
        objectAlias: "{{ . }}"
      {{- end }}
  secretObjects:
    {{- range .Values.secrets.names }}
    - secretName: {{ . | replace "/" "-" }}
      type: Opaque
      data:
        - objectName: "{{ . }}"
          key: value
    {{- end }}
{{- end }}
